version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}
        restart: always

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}

    api-migration:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        restart: on-failure
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USER: ${API_MAILER_USER}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro
            SENTRY_DSN: ${SENTRY_DSN}
        command: sh -c 'wait-for-it api-postgres:5432 -t 60 && php bin/app.php migrations:migrate --no-interaction'

    api-postgres:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data

volumes:
    api-postgres:
